version: "3.8"

services:
    react-app:
        image: react-app
        ports:
          - "3000:80"
        networks:
          -  mern-app
    nginx:
        image: nginx
        ports:
          - "80:80"

networks:
    mern-app:
        driver: bridge